openapi: 3.0.1
info:
  title: Etisalat-API
  description: Mocked APIS
  version: '1.0'
servers:
  - url: https://apis.mobivisions.com/digital2020
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]